export const recognitionTypes = {
  CORRECT_ON_LETTER: 'CORRECT_ON_LETTER',
  CORRECT_OFF_LETTER: 'CORRECT_OFF_LETTER',
  INCORRECT_ON_LETTER: 'INCORRECT_ON_LETTER',
  INCORRECT_OFF_LETTER: 'INCORRECT_OFF_LETTER',
}

export const keyboardKeys = {
  RIGHT_ARROW: 'ArrowRight',
  LEFT_ARROW: 'ArrowLeft',
  SPACE: ' ',
}

export const consentTypes = {
  NON_STUDENT_PARTICIPANT: 'NON_STUDENT_PARTICIPANT',
  PSYCH1000_STUDENT: 'PSYCH1000_STUDENT',
}

export const blockTypes = {
  SURPRIZE_BLOCK: 'SURPRIZE_BLOCK',
  MEMORANDUM_BLOCK: 'Memorandum_Block',
  MIXED_BLOCK: 'MIXED_BLOCK',
}
