export const recognitionTypes = {
  CORRECT_ON_LETTER: 'CORRECT_ON_LETTER',
  CORRECT_OFF_LETTER: 'CORRECT_OFF_LETTER',
  INCORRECT_ON_LETTER: 'INCORRECT_ON_LETTER',
  INCORRECT_OFF_LETTER: 'INCORRECT_OFF_LETTER',
}
